// Curated city list. Time zones are IANA identifiers, so the browser's
// built-in tz database handles DST rules (and regions without DST) for us.
// Any other IANA zone can still be added via search; see buildCatalog() in app.js.
window.CITIES = [
  // North America
  { city: 'Toronto', country: 'Canada', tz: 'America/Toronto' },
  { city: 'Montreal', country: 'Canada', tz: 'America/Toronto' },
  { city: 'Ottawa', country: 'Canada', tz: 'America/Toronto' },
  { city: 'Vancouver', country: 'Canada', tz: 'America/Vancouver' },
  { city: 'Calgary', country: 'Canada', tz: 'America/Edmonton' },
  { city: 'Edmonton', country: 'Canada', tz: 'America/Edmonton' },
  { city: 'Winnipeg', country: 'Canada', tz: 'America/Winnipeg' },
  { city: 'Regina', country: 'Canada', tz: 'America/Regina' },
  { city: 'Halifax', country: 'Canada', tz: 'America/Halifax' },
  { city: "St. John's", country: 'Canada', tz: 'America/St_Johns' },
  { city: 'New York', country: 'United States', tz: 'America/New_York' },
  { city: 'Washington, D.C.', country: 'United States', tz: 'America/New_York' },
  { city: 'Boston', country: 'United States', tz: 'America/New_York' },
  { city: 'Miami', country: 'United States', tz: 'America/New_York' },
  { city: 'Atlanta', country: 'United States', tz: 'America/New_York' },
  { city: 'Detroit', country: 'United States', tz: 'America/Detroit' },
  { city: 'Chicago', country: 'United States', tz: 'America/Chicago' },
  { city: 'Dallas', country: 'United States', tz: 'America/Chicago' },
  { city: 'Houston', country: 'United States', tz: 'America/Chicago' },
  { city: 'Denver', country: 'United States', tz: 'America/Denver' },
  { city: 'Phoenix', country: 'United States', tz: 'America/Phoenix' },
  { city: 'Los Angeles', country: 'United States', tz: 'America/Los_Angeles' },
  { city: 'San Francisco', country: 'United States', tz: 'America/Los_Angeles' },
  { city: 'Seattle', country: 'United States', tz: 'America/Los_Angeles' },
  { city: 'Las Vegas', country: 'United States', tz: 'America/Los_Angeles' },
  { city: 'Anchorage', country: 'United States', tz: 'America/Anchorage' },
  { city: 'Honolulu', country: 'United States', tz: 'Pacific/Honolulu' },
  { city: 'Mexico City', country: 'Mexico', tz: 'America/Mexico_City' },
  { city: 'Guadalajara', country: 'Mexico', tz: 'America/Mexico_City' },
  { city: 'Monterrey', country: 'Mexico', tz: 'America/Monterrey' },
  { city: 'Tijuana', country: 'Mexico', tz: 'America/Tijuana' },
  { city: 'Cancún', country: 'Mexico', tz: 'America/Cancun' },
  // Central America & Caribbean
  { city: 'Guatemala City', country: 'Guatemala', tz: 'America/Guatemala' },
  { city: 'San José', country: 'Costa Rica', tz: 'America/Costa_Rica' },
  { city: 'Panama City', country: 'Panama', tz: 'America/Panama' },
  { city: 'Havana', country: 'Cuba', tz: 'America/Havana' },
  { city: 'Kingston', country: 'Jamaica', tz: 'America/Jamaica' },
  { city: 'Santo Domingo', country: 'Dominican Republic', tz: 'America/Santo_Domingo' },
  { city: 'San Juan', country: 'Puerto Rico', tz: 'America/Puerto_Rico' },
  { city: 'Port of Spain', country: 'Trinidad and Tobago', tz: 'America/Port_of_Spain' },
  // South America
  { city: 'Bogotá', country: 'Colombia', tz: 'America/Bogota' },
  { city: 'Lima', country: 'Peru', tz: 'America/Lima' },
  { city: 'Quito', country: 'Ecuador', tz: 'America/Guayaquil' },
  { city: 'Caracas', country: 'Venezuela', tz: 'America/Caracas' },
  { city: 'La Paz', country: 'Bolivia', tz: 'America/La_Paz' },
  { city: 'Santiago', country: 'Chile', tz: 'America/Santiago' },
  { city: 'Buenos Aires', country: 'Argentina', tz: 'America/Argentina/Buenos_Aires' },
  { city: 'Montevideo', country: 'Uruguay', tz: 'America/Montevideo' },
  { city: 'Asunción', country: 'Paraguay', tz: 'America/Asuncion' },
  { city: 'São Paulo', country: 'Brazil', tz: 'America/Sao_Paulo' },
  { city: 'Rio de Janeiro', country: 'Brazil', tz: 'America/Sao_Paulo' },
  { city: 'Brasília', country: 'Brazil', tz: 'America/Sao_Paulo' },
  { city: 'Manaus', country: 'Brazil', tz: 'America/Manaus' },
  // Europe
  { city: 'London', country: 'United Kingdom', tz: 'Europe/London' },
  { city: 'Manchester', country: 'United Kingdom', tz: 'Europe/London' },
  { city: 'Edinburgh', country: 'United Kingdom', tz: 'Europe/London' },
  { city: 'Dublin', country: 'Ireland', tz: 'Europe/Dublin' },
  { city: 'Lisbon', country: 'Portugal', tz: 'Europe/Lisbon' },
  { city: 'Reykjavík', country: 'Iceland', tz: 'Atlantic/Reykjavik' },
  { city: 'Paris', country: 'France', tz: 'Europe/Paris' },
  { city: 'Madrid', country: 'Spain', tz: 'Europe/Madrid' },
  { city: 'Barcelona', country: 'Spain', tz: 'Europe/Madrid' },
  { city: 'Brussels', country: 'Belgium', tz: 'Europe/Brussels' },
  { city: 'Amsterdam', country: 'Netherlands', tz: 'Europe/Amsterdam' },
  { city: 'Luxembourg', country: 'Luxembourg', tz: 'Europe/Luxembourg' },
  { city: 'Berlin', country: 'Germany', tz: 'Europe/Berlin' },
  { city: 'Frankfurt', country: 'Germany', tz: 'Europe/Berlin' },
  { city: 'Munich', country: 'Germany', tz: 'Europe/Berlin' },
  { city: 'Zurich', country: 'Switzerland', tz: 'Europe/Zurich' },
  { city: 'Geneva', country: 'Switzerland', tz: 'Europe/Zurich' },
  { city: 'Vienna', country: 'Austria', tz: 'Europe/Vienna' },
  { city: 'Rome', country: 'Italy', tz: 'Europe/Rome' },
  { city: 'Milan', country: 'Italy', tz: 'Europe/Rome' },
  { city: 'Copenhagen', country: 'Denmark', tz: 'Europe/Copenhagen' },
  { city: 'Oslo', country: 'Norway', tz: 'Europe/Oslo' },
  { city: 'Stockholm', country: 'Sweden', tz: 'Europe/Stockholm' },
  { city: 'Helsinki', country: 'Finland', tz: 'Europe/Helsinki' },
  { city: 'Warsaw', country: 'Poland', tz: 'Europe/Warsaw' },
  { city: 'Prague', country: 'Czechia', tz: 'Europe/Prague' },
  { city: 'Budapest', country: 'Hungary', tz: 'Europe/Budapest' },
  { city: 'Bucharest', country: 'Romania', tz: 'Europe/Bucharest' },
  { city: 'Sofia', country: 'Bulgaria', tz: 'Europe/Sofia' },
  { city: 'Athens', country: 'Greece', tz: 'Europe/Athens' },
  { city: 'Belgrade', country: 'Serbia', tz: 'Europe/Belgrade' },
  { city: 'Zagreb', country: 'Croatia', tz: 'Europe/Zagreb' },
  { city: 'Kyiv', country: 'Ukraine', tz: 'Europe/Kyiv' },
  { city: 'Istanbul', country: 'Türkiye', tz: 'Europe/Istanbul' },
  { city: 'Ankara', country: 'Türkiye', tz: 'Europe/Istanbul' },
  { city: 'Moscow', country: 'Russia', tz: 'Europe/Moscow' },
  { city: 'Saint Petersburg', country: 'Russia', tz: 'Europe/Moscow' },
  // Middle East
  { city: 'Khobar', country: 'Saudi Arabia', tz: 'Asia/Riyadh' },
  { city: 'Riyadh', country: 'Saudi Arabia', tz: 'Asia/Riyadh' },
  { city: 'Jeddah', country: 'Saudi Arabia', tz: 'Asia/Riyadh' },
  { city: 'Dammam', country: 'Saudi Arabia', tz: 'Asia/Riyadh' },
  { city: 'Mecca', country: 'Saudi Arabia', tz: 'Asia/Riyadh' },
  { city: 'Dubai', country: 'United Arab Emirates', tz: 'Asia/Dubai' },
  { city: 'Abu Dhabi', country: 'United Arab Emirates', tz: 'Asia/Dubai' },
  { city: 'Doha', country: 'Qatar', tz: 'Asia/Qatar' },
  { city: 'Manama', country: 'Bahrain', tz: 'Asia/Bahrain' },
  { city: 'Kuwait City', country: 'Kuwait', tz: 'Asia/Kuwait' },
  { city: 'Muscat', country: 'Oman', tz: 'Asia/Muscat' },
  { city: 'Tehran', country: 'Iran', tz: 'Asia/Tehran' },
  { city: 'Baghdad', country: 'Iraq', tz: 'Asia/Baghdad' },
  { city: 'Amman', country: 'Jordan', tz: 'Asia/Amman' },
  { city: 'Beirut', country: 'Lebanon', tz: 'Asia/Beirut' },
  { city: 'Jerusalem', country: 'Israel', tz: 'Asia/Jerusalem' },
  { city: 'Tel Aviv', country: 'Israel', tz: 'Asia/Jerusalem' },
  // Africa
  { city: 'Cairo', country: 'Egypt', tz: 'Africa/Cairo' },
  { city: 'Casablanca', country: 'Morocco', tz: 'Africa/Casablanca' },
  { city: 'Algiers', country: 'Algeria', tz: 'Africa/Algiers' },
  { city: 'Tunis', country: 'Tunisia', tz: 'Africa/Tunis' },
  { city: 'Lagos', country: 'Nigeria', tz: 'Africa/Lagos' },
  { city: 'Accra', country: 'Ghana', tz: 'Africa/Accra' },
  { city: 'Dakar', country: 'Senegal', tz: 'Africa/Dakar' },
  { city: 'Addis Ababa', country: 'Ethiopia', tz: 'Africa/Addis_Ababa' },
  { city: 'Nairobi', country: 'Kenya', tz: 'Africa/Nairobi' },
  { city: 'Dar es Salaam', country: 'Tanzania', tz: 'Africa/Dar_es_Salaam' },
  { city: 'Kampala', country: 'Uganda', tz: 'Africa/Kampala' },
  { city: 'Kinshasa', country: 'DR Congo', tz: 'Africa/Kinshasa' },
  { city: 'Luanda', country: 'Angola', tz: 'Africa/Luanda' },
  { city: 'Johannesburg', country: 'South Africa', tz: 'Africa/Johannesburg' },
  { city: 'Cape Town', country: 'South Africa', tz: 'Africa/Johannesburg' },
  // South Asia
  { city: 'Dhaka', country: 'Bangladesh', tz: 'Asia/Dhaka' },
  { city: 'Chittagong', country: 'Bangladesh', tz: 'Asia/Dhaka' },
  { city: 'Mumbai', country: 'India', tz: 'Asia/Kolkata' },
  { city: 'New Delhi', country: 'India', tz: 'Asia/Kolkata' },
  { city: 'Bengaluru', country: 'India', tz: 'Asia/Kolkata' },
  { city: 'Chennai', country: 'India', tz: 'Asia/Kolkata' },
  { city: 'Kolkata', country: 'India', tz: 'Asia/Kolkata' },
  { city: 'Hyderabad', country: 'India', tz: 'Asia/Kolkata' },
  { city: 'Karachi', country: 'Pakistan', tz: 'Asia/Karachi' },
  { city: 'Lahore', country: 'Pakistan', tz: 'Asia/Karachi' },
  { city: 'Islamabad', country: 'Pakistan', tz: 'Asia/Karachi' },
  { city: 'Kathmandu', country: 'Nepal', tz: 'Asia/Kathmandu' },
  { city: 'Colombo', country: 'Sri Lanka', tz: 'Asia/Colombo' },
  { city: 'Malé', country: 'Maldives', tz: 'Indian/Maldives' },
  { city: 'Kabul', country: 'Afghanistan', tz: 'Asia/Kabul' },
  { city: 'Tashkent', country: 'Uzbekistan', tz: 'Asia/Tashkent' },
  { city: 'Almaty', country: 'Kazakhstan', tz: 'Asia/Almaty' },
  // Southeast Asia
  { city: 'Kuala Lumpur', country: 'Malaysia', tz: 'Asia/Kuala_Lumpur' },
  { city: 'Penang', country: 'Malaysia', tz: 'Asia/Kuala_Lumpur' },
  { city: 'Kuching', country: 'Malaysia', tz: 'Asia/Kuching' },
  { city: 'Singapore', country: 'Singapore', tz: 'Asia/Singapore' },
  { city: 'Manila', country: 'Philippines', tz: 'Asia/Manila' },
  { city: 'Cebu', country: 'Philippines', tz: 'Asia/Manila' },
  { city: 'Davao', country: 'Philippines', tz: 'Asia/Manila' },
  { city: 'Jakarta', country: 'Indonesia', tz: 'Asia/Jakarta' },
  { city: 'Bali (Denpasar)', country: 'Indonesia', tz: 'Asia/Makassar' },
  { city: 'Bangkok', country: 'Thailand', tz: 'Asia/Bangkok' },
  { city: 'Ho Chi Minh City', country: 'Vietnam', tz: 'Asia/Ho_Chi_Minh' },
  { city: 'Hanoi', country: 'Vietnam', tz: 'Asia/Bangkok' },
  { city: 'Phnom Penh', country: 'Cambodia', tz: 'Asia/Phnom_Penh' },
  { city: 'Yangon', country: 'Myanmar', tz: 'Asia/Yangon' },
  { city: 'Bandar Seri Begawan', country: 'Brunei', tz: 'Asia/Brunei' },
  // East Asia
  { city: 'Hong Kong', country: 'Hong Kong SAR, China', tz: 'Asia/Hong_Kong' },
  { city: 'Macau', country: 'Macau SAR, China', tz: 'Asia/Macau' },
  { city: 'Shanghai', country: 'China', tz: 'Asia/Shanghai' },
  { city: 'Beijing', country: 'China', tz: 'Asia/Shanghai' },
  { city: 'Shenzhen', country: 'China', tz: 'Asia/Shanghai' },
  { city: 'Guangzhou', country: 'China', tz: 'Asia/Shanghai' },
  { city: 'Taipei', country: 'Taiwan', tz: 'Asia/Taipei' },
  { city: 'Seoul', country: 'South Korea', tz: 'Asia/Seoul' },
  { city: 'Tokyo', country: 'Japan', tz: 'Asia/Tokyo' },
  { city: 'Osaka', country: 'Japan', tz: 'Asia/Tokyo' },
  { city: 'Ulaanbaatar', country: 'Mongolia', tz: 'Asia/Ulaanbaatar' },
  { city: 'Vladivostok', country: 'Russia', tz: 'Asia/Vladivostok' },
  // Oceania
  { city: 'Sydney', country: 'Australia', tz: 'Australia/Sydney' },
  { city: 'Melbourne', country: 'Australia', tz: 'Australia/Melbourne' },
  { city: 'Brisbane', country: 'Australia', tz: 'Australia/Brisbane' },
  { city: 'Adelaide', country: 'Australia', tz: 'Australia/Adelaide' },
  { city: 'Darwin', country: 'Australia', tz: 'Australia/Darwin' },
  { city: 'Perth', country: 'Australia', tz: 'Australia/Perth' },
  { city: 'Hobart', country: 'Australia', tz: 'Australia/Hobart' },
  { city: 'Auckland', country: 'New Zealand', tz: 'Pacific/Auckland' },
  { city: 'Wellington', country: 'New Zealand', tz: 'Pacific/Auckland' },
  { city: 'Suva', country: 'Fiji', tz: 'Pacific/Fiji' },
  { city: 'Port Moresby', country: 'Papua New Guinea', tz: 'Pacific/Port_Moresby' },
  { city: 'Guam', country: 'Guam (US)', tz: 'Pacific/Guam' },
  // Reference
  { city: 'UTC', country: 'Coordinated Universal Time', tz: 'UTC' },
];

window.DEFAULT_CITIES = [
  { city: 'Toronto', country: 'Canada', tz: 'America/Toronto' },
  { city: 'Hong Kong', country: 'Hong Kong SAR, China', tz: 'Asia/Hong_Kong' },
  { city: 'Kuala Lumpur', country: 'Malaysia', tz: 'Asia/Kuala_Lumpur' },
  { city: 'Manila', country: 'Philippines', tz: 'Asia/Manila' },
  { city: 'Khobar', country: 'Saudi Arabia', tz: 'Asia/Riyadh' },
  { city: 'Dhaka', country: 'Bangladesh', tz: 'Asia/Dhaka' },
];
